# Generated by Django 5.1.3 on 2024-11-28 13:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(default='XXXXX-00000', max_length=11, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('origin', models.CharField(default='XXXX', max_length=255)),
                ('destination', models.CharField(default='XXXX', max_length=255)),
                ('departure_time', models.TimeField(default='00:00:00')),
                ('arrival_time', models.TimeField(default='00:00:00')),
                ('train_number', models.IntegerField(default=0)),
                ('trip_type', models.CharField(choices=[('ITR', 'ITR'), ('LTR', 'LTR'), ('XXX', 'XXX')], default='XXX', max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(default='XXXX-000', max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('route_type', models.CharField(choices=[('IR', 'IR'), ('LR', 'LR'), ('XX', 'XX')], default='XX', max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('expected_duration', models.TimeField(default='00:00:00')),
                ('starting_station', models.CharField(default='XXXX', max_length=255)),
                ('ending_station', models.CharField(default='XXXX', max_length=255)),
                ('number_of_trips', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TripSchedule',
            fields=[
                ('trip_schedule_id', models.CharField(default='XXXXX', max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('date', models.DateField(default='2010-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='InterTownTrip',
            fields=[
                ('itr_trip', models.OneToOneField(default='XXXXX-00000', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inter_town_trips', serialize=False, to='TripScheduling.trip')),
                ('cost_in_lion_coins', models.IntegerField(default=0)),
                ('duration_time_in_minutes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LocalTrip',
            fields=[
                ('ltr_trip', models.OneToOneField(default='XXXXX-00000', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='local_trips', serialize=False, to='TripScheduling.trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='route_id',
            field=models.ForeignKey(default='XXXX', on_delete=django.db.models.deletion.CASCADE, related_name='trips', related_query_name='tripss', to='TripScheduling.route'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_schedule_id',
            field=models.ForeignKey(default='XXXXX', on_delete=django.db.models.deletion.CASCADE, related_name='trips', related_query_name='tripss', to='TripScheduling.tripschedule'),
        ),
    ]
