# Generated by Django 5.1.3 on 2024-11-19 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripSchedule',
            fields=[
                ('trip_schedule_id', models.IntegerField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
