# Generated by Django 5.1.3 on 2024-11-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripschedule',
            name='date',
            field=models.DateField(default='2010-01-01', unique=True),
        ),
    ]
