# Generated by Django 5.1.3 on 2024-11-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripschedule',
            name='date',
            field=models.DateField(),
        ),
    ]
