# Generated by Django 5.1.3 on 2024-11-19 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0002_alter_tripschedule_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterTownTrip',
            fields=[
                ('itr_trip_id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
        migrations.AlterField(
            model_name='tripschedule',
            name='trip_schedule_id',
            field=models.IntegerField(default='XXXXX', max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
