# Generated by Django 5.0.2 on 2024-11-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0002_alter_trip_options_alter_intertowntrip_itr_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='train_number',
            field=models.IntegerField(default=0),
        ),
    ]
