# Generated by Django 5.1.3 on 2024-11-21 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0003_alter_trip_train_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('ITR', 'ITR'), ('LTR', 'LTR'), ('XXX', 'XXX')], default='XXX', max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
