# Generated by Django 5.1.3 on 2024-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0004_alter_trip_trip_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intertowntrip',
            name='duration_time',
        ),
        migrations.AddField(
            model_name='intertowntrip',
            name='duration_time_in_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
