# Generated by Django 5.1.3 on 2024-11-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0004_alter_tripschedule_trip_schedule_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='trip_schedule_id',
            new_name='trip_schedule',
        ),
    ]
