# Generated by Django 5.1.3 on 2024-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0004_alter_tripschedule_trip_schedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripschedule',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
