# Generated by Django 5.1.3 on 2024-11-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0005_rename_trip_schedule_id_trip_trip_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='trip_schedule',
            new_name='trip_schedule_id',
        ),
    ]
