# Generated by Django 5.1.3 on 2024-11-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0006_rename_trip_schedule_trip_trip_schedule_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intertowntrip',
            old_name='itr_trip',
            new_name='itr_trip_id',
        ),
        migrations.RenameField(
            model_name='localtrip',
            old_name='ltr_trip',
            new_name='ltr_trip_id',
        ),
    ]
