# Generated by Django 5.1.3 on 2024-11-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0007_rename_itr_trip_intertowntrip_itr_trip_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intertowntrip',
            old_name='itr_trip_id',
            new_name='itr_trip',
        ),
        migrations.RenameField(
            model_name='localtrip',
            old_name='ltr_trip_id',
            new_name='ltr_trip',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='route_id',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_schedule_id',
            new_name='trip_schedule',
        ),
    ]
