# Generated by Django 5.1.3 on 2024-11-19 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0008_alter_tripschedule_trip_schedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='intertowntrip',
            name='arrival_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='intertowntrip',
            name='departure_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='intertowntrip',
            name='destination',
            field=models.CharField(default='XXXX', max_length=255),
        ),
        migrations.AddField(
            model_name='intertowntrip',
            name='origin',
            field=models.CharField(default='XXXX', max_length=255),
        ),
        migrations.AddField(
            model_name='intertowntrip',
            name='train_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='intertowntrip',
            name='itr_trip_id',
            field=models.CharField(default='XXXXX-00000', max_length=11, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='tripschedule',
            name='date',
            field=models.DateField(default='2010-01-01'),
        ),
    ]
