# Generated by Django 5.1.3 on 2024-11-19 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0009_intertowntrip_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intertowntrip',
            name='train_number',
            field=models.IntegerField(default=0, max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
