# Generated by Django 5.1.3 on 2024-11-19 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0010_alter_intertowntrip_train_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='intertowntrip',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intertowntrip',
            name='duration_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='intertowntrip',
            name='trip_schedule',
            field=models.ForeignKey(default='XXXXX', on_delete=django.db.models.deletion.CASCADE, related_name='inter_town_trips', to='TripScheduling.tripschedule'),
        ),
        migrations.CreateModel(
            name='LocalTrip',
            fields=[
                ('local_trip_id', models.CharField(default='XXXXX-00000', max_length=11, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('origin', models.CharField(default='XXXX', max_length=255)),
                ('destination', models.CharField(default='XXXX', max_length=255)),
                ('departure_time', models.TimeField(default='00:00:00')),
                ('arrival_time', models.TimeField(default='00:00:00')),
                ('train_number', models.IntegerField(default=0, max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
                ('trip_schedule', models.ForeignKey(default='XXXXX', on_delete=django.db.models.deletion.CASCADE, related_name='local_trips', to='TripScheduling.tripschedule')),
            ],
        ),
    ]
