# Generated by Django 5.1.3 on 2024-11-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripScheduling', '0011_intertowntrip_cost_intertowntrip_duration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intertowntrip',
            name='train_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='localtrip',
            name='train_number',
            field=models.IntegerField(default=0),
        ),
    ]
